# Generated by Django 6.0.5 on 2026-06-17 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('workspaces', '0007_access_grant_roles_remove_legacy_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'board', 'column', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('inbox', 'Inbox'), ('workspace', 'Workspace'), ('department', 'Department'), ('project', 'Project')], default='inbox', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_boards', to='organizations.department')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_boards', to='workspaces.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_boards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'board_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskboard'),
        ),
        migrations.CreateModel(
            name='TaskColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=80)),
                ('semantic_type', models.CharField(choices=[('todo', 'To do'), ('active', 'Active'), ('review', 'Review'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], default='todo', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.taskboard')),
            ],
            options={
                'ordering': ['board', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.taskcolumn'),
        ),
        migrations.CreateModel(
            name='TaskObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_task_observers', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_users', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_task_assignee')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskboard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('board_type__in', ['inbox', 'workspace']), ('department__isnull', True), ('project__isnull', True)), models.Q(('board_type', 'department'), ('department__isnull', False), ('project__isnull', True)), models.Q(('board_type', 'project'), ('department__isnull', True), ('project__isnull', False)), _connector='OR'), name='task_board_context_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='taskboard',
            constraint=models.UniqueConstraint(condition=models.Q(('board_type__in', ['inbox', 'workspace'])), fields=('workspace', 'board_type'), name='unique_system_task_board_per_workspace_type'),
        ),
        migrations.AddConstraint(
            model_name='taskboard',
            constraint=models.UniqueConstraint(condition=models.Q(('board_type', 'department'), ('department__isnull', False)), fields=('workspace', 'department'), name='unique_department_task_board_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='taskboard',
            constraint=models.UniqueConstraint(condition=models.Q(('board_type', 'project'), ('project__isnull', False)), fields=('workspace', 'project'), name='unique_project_task_board_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='taskcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'key'), name='unique_task_column_key_per_board'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'board', 'column'], name='tasks_task_workspa_46793c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'priority'], name='tasks_task_workspa_040f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'due_date'], name='tasks_task_workspa_fab1e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskobserver',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_observer'),
        ),
    ]
