# Generated by Django 6.0.5 on 2026-06-22 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_task_discussions(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    TaskDiscussion = apps.get_model("tasks", "TaskDiscussion")
    TaskDiscussion.objects.bulk_create(
        (TaskDiscussion(task_id=task_id) for task_id in Task.objects.values_list("id", flat=True)),
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['task', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/comments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskcomment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_comment_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['comment', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='tasks.task')),
            ],
        ),
        migrations.RunPython(create_existing_task_discussions, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TaskDiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_discussion_messages', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.taskdiscussion')),
            ],
            options={
                'ordering': ['discussion', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDiscussionMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/discussions/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskdiscussionmessage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_discussion_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['message', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taskc_task_id_3f97e8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdiscussionmessage',
            index=models.Index(fields=['discussion', 'created_at'], name='tasks_taskd_discuss_c2b524_idx'),
        ),
    ]
