from django.urls import path

from .views import (
    add_company_access_grant,
    add_department_access_grant,
    add_user_access_grant,
    remove_access_grant,
    workspace_chats,
    workspace_create,
    workspace_dashboard,
    workspace_departments,
    workspace_projects,
    workspace_settings,
    workspace_settings_members_access,
    workspace_storage,
    workspace_task_create,
    workspace_task_edit,
    workspace_task_move,
    workspace_tasks,
    workspace_team_members,
    workspace_teams,
)


app_name = "workspaces"

urlpatterns = [
    path("", workspace_dashboard, name="shell"),
    path("new-workspace/", workspace_create, name="workspace_create"),
    # Transitional routes for old bookmarks and integrations. Canonical UI links never use these.
    path("workspaces/dashboard/", workspace_dashboard, name="dashboard"),
    path("workspaces/departments/", workspace_departments, name="departments"),
    path("workspaces/tasks/", workspace_tasks, name="tasks"),
    path("workspaces/tasks/create/", workspace_task_create, name="task-create"),
    path("workspaces/tasks/<int:task_id>/edit/", workspace_task_edit, name="task-edit"),
    path("workspaces/tasks/<int:task_id>/move/", workspace_task_move, name="task-move"),
    path("workspaces/projects/", workspace_projects, name="projects"),
    path("workspaces/projects/new/", workspace_projects, {"mode": "create"}, name="project-create"),
    path("workspaces/projects/<int:project_id>/", workspace_projects, name="project-detail"),
    path("workspaces/projects/<int:project_id>/edit/", workspace_projects, {"mode": "edit"}, name="project-edit"),
    path("workspaces/teams/", workspace_teams, name="teams"),
    path("workspaces/teams/<int:team_id>/", workspace_teams, name="team-detail"),
    path("workspaces/teams/<int:team_id>/members/", workspace_team_members, name="team-members"),
    path("workspaces/chats/", workspace_chats, name="chats"),
    path("workspaces/storage/", workspace_storage, name="storage"),
    path("workspaces/settings/", workspace_settings, name="settings"),
    path("workspaces/settings/members-access/", workspace_settings_members_access, name="settings-members-access"),
    path("workspaces/settings/access/company/", add_company_access_grant, name="add-company-access"),
    path("workspaces/settings/access/department/", add_department_access_grant, name="add-department-access"),
    path("workspaces/settings/access/user/", add_user_access_grant, name="add-user-access"),
    path("workspaces/settings/access/<int:grant_id>/remove/", remove_access_grant, name="remove-access"),

    path("<slug:workspace_slug>/", workspace_dashboard, name="dashboard"),
    path("<slug:workspace_slug>/departments/", workspace_departments, name="departments"),
    path("<slug:workspace_slug>/tasks/", workspace_tasks, name="tasks"),
    path("<slug:workspace_slug>/tasks/create/", workspace_task_create, name="task-create"),
    path("<slug:workspace_slug>/tasks/<int:task_id>/edit/", workspace_task_edit, name="task-edit"),
    path("<slug:workspace_slug>/tasks/<int:task_id>/move/", workspace_task_move, name="task-move"),
    path("<slug:workspace_slug>/projects/", workspace_projects, name="projects"),
    path("<slug:workspace_slug>/projects/new/", workspace_projects, {"mode": "create"}, name="project-create"),
    path("<slug:workspace_slug>/projects/<int:project_id>/", workspace_projects, name="project-detail"),
    path("<slug:workspace_slug>/projects/<int:project_id>/edit/", workspace_projects, {"mode": "edit"}, name="project-edit"),
    path("<slug:workspace_slug>/teams/", workspace_teams, name="teams"),
    path("<slug:workspace_slug>/teams/<int:team_id>/", workspace_teams, name="team-detail"),
    path("<slug:workspace_slug>/teams/<int:team_id>/members/", workspace_team_members, name="team-members"),
    path("<slug:workspace_slug>/chats/", workspace_chats, name="chats"),
    path("<slug:workspace_slug>/storage/", workspace_storage, name="storage"),
    path("<slug:workspace_slug>/settings/", workspace_settings, name="settings"),
    path("<slug:workspace_slug>/settings/members-access/", workspace_settings_members_access, name="settings-members-access"),
    path("<slug:workspace_slug>/settings/access/company/", add_company_access_grant, name="add-company-access"),
    path("<slug:workspace_slug>/settings/access/department/", add_department_access_grant, name="add-department-access"),
    path("<slug:workspace_slug>/settings/access/user/", add_user_access_grant, name="add-user-access"),
    path("<slug:workspace_slug>/settings/access/<int:grant_id>/remove/", remove_access_grant, name="remove-access"),
]
