# Generated by Django 6.0.5 on 2026-06-11 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_access_grants', to='organizations.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_access_grants', to='organizations.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_access_grants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_teams', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='workspaces.workspaceaccessgrant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspaceteam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspaceaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('department__isnull', True), ('user__isnull', True)), models.Q(('company__isnull', True), ('department__isnull', False), ('user__isnull', True)), models.Q(('company__isnull', True), ('department__isnull', True), ('user__isnull', False)), _connector='OR'), name='workspace_access_grant_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='workspaceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('workspace', 'company'), name='unique_workspace_access_company'),
        ),
        migrations.AddConstraint(
            model_name='workspaceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('workspace', 'department'), name='unique_workspace_access_department'),
        ),
        migrations.AddConstraint(
            model_name='workspaceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workspace', 'user'), name='unique_workspace_access_user'),
        ),
        migrations.AddConstraint(
            model_name='workspaceteam',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_workspace_team_slug'),
        ),
        migrations.AddConstraint(
            model_name='workspaceteammember',
            constraint=models.UniqueConstraint(fields=('team', 'access_grant'), name='unique_workspace_team_member_grant'),
        ),
    ]
