# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("workspaces", "0003_project_created_by_project_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_projects",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="kind",
            field=models.CharField(
                choices=[("regular", "Regular"), ("department", "Department")],
                default="regular",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("department__isnull", True), ("kind", "regular"))
                    | models.Q(("department__isnull", False), ("kind", "department"))
                ),
                name="project_kind_department_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("department__isnull", False), ("kind", "department")),
                fields=("workspace", "department"),
                name="unique_department_project_per_workspace",
            ),
        ),
    ]
