# Generated by Codex on 2026-06-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_project_department_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_department_project_per_workspace",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project_kind_department_consistency",
        ),
        migrations.RemoveField(
            model_name="project",
            name="department",
        ),
        migrations.RemoveField(
            model_name="project",
            name="kind",
        ),
    ]
