# Generated by Codex on 2026-06-15

from django.db import migrations, models
import django.db.models.deletion


def infer_company_workspaces(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    WorkspaceAccessGrant = apps.get_model("workspaces", "WorkspaceAccessGrant")

    for workspace in Workspace.objects.all():
        company_ids = list(
            WorkspaceAccessGrant.objects.filter(
                workspace=workspace,
                company__isnull=False,
            )
            .order_by()
            .values_list("company_id", flat=True)
            .distinct()
        )
        if len(company_ids) == 1:
            workspace.company_id = company_ids[0]
            workspace.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("workspaces", "0005_remove_project_department_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="organizations.company",
            ),
        ),
        migrations.RunPython(infer_company_workspaces, migrations.RunPython.noop),
    ]
